language: python
python:
  - "3.6.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest==5.3.2
# command to run tests
script: 
  - python -m unittest discover
  - pytest tests/integration/test_extreme_thetas_inference.py
